rencana fitur baru
-membuat template admin
-membuat login laravel
-membuat fitur animasi
-membuat fitur pencarian
-membuat fitur
-ini adalah fitur gas
-fitur pengembangan
-fitur bersama
-oke gan
-menambah crud
-menambahkan delete